## 4. TO - DO - Task
Please complete all the problem listed below.

### 4.1 Exercise on Functions:
Task - 1:

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
- Conversion Options:
1. Length:
- Convert meters (m) to feet (ft).
- Convert feet (ft) to meters (m).
2. Weight:
- Convert kilograms (kg) to pounds (lbs).
- Convert pounds (lbs) to kilograms (kg).
3. Volume:
- Convert liters (L) to gallons (gal).
- Convert gallons (gal) to liters (L).

In [ ]:
def length_conversion (value, unit):
  '''
  Convert length between meter and feet

  Parameters:
      value (int): Numberic value to be converted
      unit(string): Unit of the input value

  Returns:
      Converted value.
  '''
  try:
    if unit == "m":
      return value * 3.28084
    elif unit == "ft":
      return value / 3.28084
    else:
      print("Invalid unit")
  except ValueError as e:
    print(f"Error: {e}")

def weight_conversion(value, unit):
  '''
  Convert weight between kilograms and pounds

  Parameters:
      value (int): Numeric value to be converted
      unit(string): unit of the input value

  Returns:
      Converted value
  '''
  try:
    if unit == "kg":
      return value * 2.20462
    elif unit == "lbs":
      return value / 2.20462
    else:
      print("Invalid unit")
  except ValueError as e:
    print(f"Error: {e}")

def volume_conversion(value, unit):
  '''
  Convert volume between liters and gallons.

  Parameters:
    value (int): Numeric value to be converted
    unit(string): unit of the input value

  Returns:
    Converted value
  '''
  try:
    if unit == 'l':
      return value * 0.264172
    elif unit == 'gal':
      return value / 0.264172
    else:
      print("Invalid unit")
  except ValueError as e:
    print("Error: ", e)

def main():
  '''
  Main function to handle user input and perform conversions.

  '''
  while True:
    try:
      print("\nChoose conversion type:")
      print("1. Length (meters to feet, feet to meters)")
      print("2. weight (kilograms to pounds, pounds to kilograms)")
      print("3. Volume (liters to gallons, gallons to liters)")
      print("0. Exit Program")

      choice = input ("Enter your choice (1/2/3/0): ").strip()
      if choice == '0':
        print("Goodbye!")
        break

      if choice == '1':
        unit = input("Enter the unit (m/ft): ").strip().lower()
        value = float(input("Enter the value to convert: "))
        result = length_conversion(value, unit)
        unit_to_be = 'ft' if unit == 'm' else 'm'

      elif choice == '2':
        unit = input("Enter th unit (kg/lbs): ").strip().lower()
        value = float(input("Enter the value to convert: "))
        result = weight_conversion(value, unit)
        unit_to_be = 'lbs' if unit == 'kg' else 'kg'

      elif choice == '3':
        unit = input("Enter the unit (l/gal): ").strip().lower()
        value = float(input("Enter the value to convert: "))
        result = volume_conversion(value, unit)
        unit_to_be = 'gal' if unit == 'l' else 'l'

      else:
        print("Invalid choice. Please select 1, 2 or 3.")
        return

      print(f"Converted value: {result:.2f} {unit_to_be}")

    except (ValueError, TypeError) as e:
      print("Error: ", e)

if __name__ == "__main__":
  main()




Choose conversion type:
1. Length (meters to feet, feet to meters)
2. weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
0. Exit Program
Enter your choice (1/2/3/0): 1
Enter the unit (m/ft): asdasd
Enter the value to convert: 25
Invalid unit
Error:  unsupported format string passed to NoneType.__format__

Choose conversion type:
1. Length (meters to feet, feet to meters)
2. weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
0. Exit Program
Enter your choice (1/2/3/0): 1
Enter the unit (m/ft): m
Enter the value to convert: asdasdasd
Error:  could not convert string to float: 'asdasdasd'

Choose conversion type:
1. Length (meters to feet, feet to meters)
2. weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
0. Exit Program
Enter your choice (1/2/3/0): 1
Enter the unit (m/ft): m
Enter the value to convert: 25
Converted value: 82.02 ft

Choose con

Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def list_num():
  ''''
  Get a list of number from the user and return it
  '''
  try:
    number = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
    if len(number) == 0:
      raise ValueError("The list cannot be empty.")
    return number
  except ValueError:
    print("Invalid input. Please enter only numbers.")
    return list_num()

def main():
  '''
  Main function for user choice
  '''
  while True:
    try:
      print ("\nChoose an operation")
      print("1. Sum")
      print("2. Average")
      print("3. Maximum")
      print("4. Minimum")
      print("0. Quit")

      choice = input("Enter choice (1-4)")

      if choice == "0":
        print("Goodbye!")
        break

      numbers = list_num()

      if choice == "1":
        print("Sum: ", sum(numbers))
      elif choice == "2":
        print("Average: ", sum(numbers)/len(numbers))
      elif choice == "3":
        print("Maximum: ", max(numbers))
      elif choice == "4":
        print("Minimum: ", min(numbers))
      else:
        print("Invalid choice. Please try again.")
    except ValueError as e:
      print("Error: ",e)

if __name__ == "__main__":
  main()



Choose an operation
1. Sum
2. Average
3. Maximum
4. Minimum
0. Quit
Enter choice (1-4)asdas
Enter a list of numbers separated by spaces: 1 2 3 4 5
Invalid choice. Please try again.

Choose an operation
1. Sum
2. Average
3. Maximum
4. Minimum
0. Quit
Enter choice (1-4)1
Enter a list of numbers separated by spaces: asdasdasd
Invalid input. Please enter only numbers.
Enter a list of numbers separated by spaces: 1 2 3 4 5
Sum:  15

Choose an operation
1. Sum
2. Average
3. Maximum
4. Minimum
0. Quit
Enter choice (1-4)0
Goodbye!


## 4.2 Exercise on List Manipulation:
### 1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.
- Requirements:
 - Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
 - Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_element(lst):
  '''
  Take list and extract every other element
  '''
  return lst[::2]

example_list = [1,2,3,4,5,6]
result = extract_element(example_list)
print(result)

[1, 3, 5]


### 2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

- Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
- Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def slice_list(lst, start, end):
  '''
  Return sliced list

  Parameter:
    lst: list to be sliced
    start: starting index, from where the list should be sliced
    end: ending index, till where the list should be sliced
  '''
  return lst[start:end+1]

lists2 = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
start_index = int(input("Enter the starting index for slicing: "))
end_index = int(input("Enter the ending index for slicing: "))
print(slice_list(lists2, start_index, end_index))

Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Enter the starting index for slicing: 2
Enter the ending index for slicing: 4
[3, 4, 5]


### 3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

• Requirements:
- Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
  '''
  Reverse the order of the list
  '''
  return lst[::-1]

list3 = [1, 2, 3, 4, 5]
print(reverse_list(list3))

[5, 4, 3, 2, 1]


### 4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:
- Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def sublist(lst):
  '''
  Returning sublist with list as parameter
  '''
  return lst[1:-1]

lst1 = [1, 2, 3, 4, 5]
print(sublist(lst1))

[2, 3, 4]


### 5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

• Requirements:
- Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
- Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def first_n(lst, n):
  '''
  Return the first n elements of the list

  Parameters:
    lst: numerical list
    n: n elements
  '''
  return lst[:n]

lst2 = list(map(int, input("Enter the number with spaces: ").split()))
n = int(input("Enter the number of elements to be extracted: "))
print(first_n(lst2,n))

Enter the number with spaces: 1 2 3 4 5
Enter the number of elements to be extracted: 3
[1, 2, 3]


### 6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:
- Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
- Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def last_n(lst, n):
  '''
  Return the last n element of the list

  Parameters:
    lst: numerical list
    n: n elements
  '''
  return lst[-n:]


lst2 = list(map(int, input("Enter the number with spaces: ").split()))
n = int(input("Enter the number of elements to be extracted: "))
print(last_n(lst3, n))

Enter the number with spaces: 1 2 3 4 5 
Enter the number of elements to be extracted: 2
[4, 5]


### 7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:
- Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
  '''
  Return a list containing every second element in reverse

  Parameters:
    lst: Input list.

  '''
  return lst [-2::-2]

lst4 = [1,2,3,4,5,6]
print(reverse_skip(lst4))

[5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

- Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

- Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
  '''
  Flatten a nested list into a single list.

  Parameters:
    lst: The nested list.
  '''
  flat_list = []
  for sublist in lst:
    flat_list.extend(sublist)
  return flat_list

example_list = [[1, 2], [3, 4], [5]]
print(flatten(example_list))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:
- Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
- Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def nested_element(lst, indices):
  '''
  Extracts a specific element from nested list given its indices.

  Parameters:
    lst : the nested list
    indices : Position to access
  '''
  for index in indices:
    lst = lst[index]
  return lst

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices =[1,2]
print(nested_element(lst, indices))

6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:
- Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_element(lst):
  '''
  Sum all element in the nested list

  Parameter:
    lst: list to be summed
  '''
  sum = 0
  for lsts in lst:
    if isinstance(lsts, list):
      sum += sum_element(lsts)
    else:
      sum = sum + lsts
  return sum
lst = [[1, 2], [3, [4, 5]], 6]
print(sum_element(lst))

21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:
- Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
- Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
  '''
  Remove specific element from the list

  Parameter:
    lst: The nested list
    elem: The element to remove

  Returns:
    A new list with removed element
  '''
  result = []
  for item in lst:
    if (isinstance(item, list)):
      sublist = remove_element(item, elem)
      result.append(sublist)
    elif item != elem:
      result.append(item)
  return result

lst =  [[1, 2], [3, 2], [4, 5]]
elem = 2

print(remove_element(lst, elem))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:
- Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
  '''
  Find the maximum element in the list

  Parameters:
    lst: A List

  Returns:
    The maximum number from the list
  '''
  current_max = None
  for item in lst:
    if isinstance (item, list):
      value = find_max(item)
    else:
      value = item

    if current_max is None or value > current_max:
      current_max = value
  return current_max

lst = [[1, 2], [3, [4, 5]], 6]
print(find_max(lst))

6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:
- Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
- Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def occurrences(lst, elem):
  '''
  Count the occurences of elem

  Parameters:
    lst: The nested list
    elem: the element to count

  Returns:
    The count of occurrences of element
  '''

  count = 0
  for item in lst:
    if isinstance(item, list):
      count += occurrences(item, elem)
    elif item == elem:
      count += 1
  return count

print(occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:
- Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
- Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def flatten(lst):
  '''
  Flatten a nested list into a single list.

  Parameters:
    lst: The nested list.
  '''
  flat_list = []
  for sublist in lst:
    if isinstance(sublist, list):
      flat_list.extend(flatten(sublist))
    else:
      flat_list.append(sublist)
  return flat_list

print(flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

• Requirements:
- Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
- Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def flatten(lst):
  '''
  Flatten a nested list into a single list.

  Parameters:
    lst: The nested list.
  '''
  flat_list = []
  for sublist in lst:
    if isinstance(sublist, list):
      flat_list.extend(flatten(sublist))
    else:
      flat_list.append(sublist)
  return flat_list

def average_nested(lst):
  '''
  calculate average of all elements in the list

  Parameters:
    lst: The nested list.

  '''

  return sum(flatten(lst)) / len (flatten(lst))

print(average_nested([[[1, 2], [3, 4]], [[5, 6]]]))

3.5


### 10 To - Do - NumPy
Please complete all the problems listed below:

**10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

empty_array = np.empty((2,2))

empty_array

array([[2.25799235e-316, 0.00000000e+000],
       [4.94065646e-324, 6.87734002e-310]])

2. Initialize an all one array with size 4X2.

In [ ]:
one_array = np.ones((4,2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
arry = np.full((3,3), 7)
arry

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
alike_arry = np.zeros_like(arry)
alike_arry

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
alike_arry1 = np.ones_like(arry)
alike_arry1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]

list_arry = np.array(new_list)
list_arry

array([1, 2, 3, 4])

**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
arry1 = np.arange(10, 49)
arry1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
arry_val = np.arange(9)

matrix_3x3 = np.reshape(arry_val, (3,3))
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
arry_30 = np.random.random(30)
mean_arry = arry_30.mean()

print("Random Array: \n", arry_30)
print("Mean of the random Array: ", mean_arry)

Random Array: 
 [0.00550818 0.15688489 0.36090742 0.19943947 0.63810594 0.49066715
 0.11544092 0.17497285 0.17454992 0.47761425 0.58725419 0.72804627
 0.17456046 0.91787578 0.07820658 0.68989617 0.3605269  0.25392884
 0.81713736 0.57273798 0.06549922 0.47363774 0.29082029 0.17822064
 0.1057477  0.22011591 0.60979932 0.28917145 0.72267907 0.41986553]
Mean of the random Array:  0.3783272794967372


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
arry_10 = np.random.random((10, 10))

max_num = arry_10.max()
min_num = arry_10.min()

print(arry_10)
print(max_num)
print(min_num)

[[0.49622545 0.91753918 0.31586007 0.09674763 0.81394166 0.86362699
  0.2701238  0.75867009 0.75076938 0.70861439]
 [0.52284973 0.40453898 0.6823318  0.73615915 0.42476679 0.23878679
  0.56728034 0.82387581 0.19830811 0.1691481 ]
 [0.71166027 0.07280957 0.18072618 0.1463371  0.54634162 0.49593952
  0.46338014 0.28034244 0.61836355 0.19071912]
 [0.48482737 0.28354743 0.68217596 0.31068062 0.20951313 0.22766115
  0.67804307 0.45011596 0.68888575 0.95585252]
 [0.65944687 0.4037135  0.78505134 0.0316881  0.54721782 0.7911794
  0.55933842 0.08312087 0.61151652 0.33408842]
 [0.47862825 0.0845563  0.00646824 0.95923067 0.7925182  0.47633694
  0.11768695 0.68791381 0.30543307 0.54822324]
 [0.62209907 0.56278992 0.21182326 0.2526327  0.27592075 0.75553594
  0.1297726  0.12499271 0.43365982 0.33552483]
 [0.1816744  0.10919587 0.50501953 0.38605734 0.90115975 0.62776331
  0.86463585 0.57213567 0.59445979 0.96365843]
 [0.2684079  0.49879659 0.91700193 0.82429492 0.92341625 0.31888929
  0.4398698  

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
new_arry = np.zeros(10)
new_arry[5] = 1
new_arry

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1,2,0,0,4,0]
arr[::-1]

[0, 4, 0, 0, 2, 1]

8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
new_arr = np.zeros((5, 5))
new_arr[0, :] = 1
new_arr[-1, :] = 1
new_arr[:, 0] = 1
new_arr[:, -1] = 1

new_arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Problem - 3: Array Operations:
For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

add_x_y = np.add(x,y)
print("Sum of array x and y: ", add_x_y)

v = np.array([9,10])
w = np.array([11,12])
add_v_w = np.add(v, w)
print("Sum of array v and w: ", add_v_w)

Sum of array x and y:  [[ 6  8]
 [10 13]]
Sum of array v and w:  [20 22]


2. Subtract the two array.

In [ ]:
sub_x_y = np.subtract(x,y)
print("Differences of array x and y: ", sub_x_y)

sub_v_w = np.subtract(v,w)
print("Differences of array v and w: ", sub_v_w)

Differences of array x and y:  [[-4 -4]
 [-4 -3]]
Differences of array v and w:  [-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
multiply_x = x * 1
multiply_y = y * 2
multiply_v = v * 1
multiply_w = w * 2

print("Multiplication of array:\n", multiply_x, "\n\n",  multiply_y, "\n\n",
      multiply_v, "\n\n", multiply_w)

Multiplication of array:
 [[1 2]
 [3 5]] 

 [[10 12]
 [14 16]] 

 [ 9 10] 

 [22 24]


4. Find the square of each element of the array.

In [ ]:
square_x = np.square(x)
square_y = np.square(y)
square_v = np.square(v)
square_w = np.square(w)

print("Square of each element of the array:\n", square_x, "\n\n",
      square_y, "\n\n", square_v, "\n\n", square_w)

Square of each element of the array:
 [[ 1  4]
 [ 9 25]] 

 [[25 36]
 [49 64]] 

 [ 81 100] 

 [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
dot_vw = np.dot(v, w)
dot_xy = np.dot(x, y)
dot_xv = np.dot(x, v)

print("Dot product between v and w: ", dot_vw)
print("Dot product between x and v: ", dot_xv)
print("Dot product between x and y: ", dot_xy)

Dot product between v and w:  219
Dot product between x and v:  [29 77]
Dot product between x and y:  [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
concat_xy = np.concatenate((x, y))
concat_vw = np.vstack((v, w))
print("Concatenation of x and y along row: ", concat_xy)
print("Concatenation of v and w along coloumn: ", concat_vw)

Concatenation of x and y along row:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along coloumn:  [[ 9 10]
 [11 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
concat_xv = np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## Problem - 4: Matrix Operations:
• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)
proof = np.dot(A, A_inv)
proof = np.round(proof, 6)

print("A * A_inc:\n", proof)

A * A_inc:
 [[1. 0.]
 [0. 1.]]


This is approximately the identity matrix
I
I, with minor numerical errors due to floating-point precision.

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB = \n", AB)
print("BA = \n", BA)

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]


3. Prove (AB)T = BTAT

In [ ]:
AB_T = AB.T
B_T = B.T
A_T = A.T

B_T_A_T = np.dot(B_T, A_T)

print("(AB)^T = \n", AB_T)
print("\nB^T A^T = \n", B_T_A_T)

(AB)^T = 
 [[23 51]
 [13 29]]

B^T A^T = 
 [[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
A = np.array([[2, -3, 1],
             [1, -1, 2],
             [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print(f"x = {X[0]}, y = {X[1]} and z = {X[2]}")

x = 2.0, y = 1.0 and z = -2.0


### 10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
- Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [2]:
import time

# Generate two large lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# Start timing
start_time = time.time()

# Perform element-wise addition
sum_list = [a + b for a, b in zip(list1, list2)]
print("Python list addition time:", time.time() - start_time)

Python list addition time: 0.21726775169372559


In [4]:
import numpy as np

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start = time.time()
sum_arr = arr1 + arr2
print("NumPy array addition time:", time.time() - start)

NumPy array addition time: 0.002550363540649414


2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [5]:
start = time.time()

product_list = [a * b for a,b in zip(list1, list2)]
print("Python list multiplication time:", time.time() - start)

Python list multiplication time: 0.044583797454833984


In [6]:
start = time.time()
product_arr = arr1 * arr2
print("NumPy array addition time:", time.time() - start)

NumPy array addition time: 0.001386880874633789


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [8]:
start = time.time()
dot_product = sum(a * b for a, b in zip(list1, list2))
print("Python list dot product time:", time.time() - start)

Python list dot product time: 0.05343794822692871


In [9]:
start = time.time()
dot_product = np.dot(arr1, arr2)
print("NumPy array dot product time:", time.time() - start)

NumPy array dot product time: 0.0014934539794921875


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [18]:
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i + j for j in range(1000)] for i in range(1000)]

start = time.time()
mul_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)]
              for row in matrix1]

print("Python list matrix multiplication:", time.time() - start)

Python list matrix multiplication: 83.06312584877014


In [17]:
np_matrix1 = np.random.random((1000, 1000))
np_matrix2 = np.random.random((1000,1000))

start = time.time()
mul_matrix = np.dot(matrix1, matrix2)

print("Numpy array matrix multiplication:", time.time() - start)

Numpy array matrix multiplication: 1.0574965476989746
